all:
	g++ megalovania.cpp quicksort.cpp bucketsort.cpp countingsort.cpp bubblesort.cpp insertsort.cpp mergesort.cpp heapsort.cpp vector_fill_utils.cpp timer.cpp -std=c++11 -o trabalho1.exe

test:
	g++ main_tests.cpp quicksort.cpp bucketsort.cpp countingsort.cpp bubblesort.cpp insertsort.cpp mergesort.cpp heapsort.cpp vector_fill_utils.cpp timer.cpp -std=c++11 -o trabalho1.exe

debug:
	g++ -g main_tests.cpp quicksort.cpp bucketsort.cpp countingsort.cpp bubblesort.cpp insertsort.cpp mergesort.cpp heapsort.cpp vector_fill_utils.cpp timer.cpp -std=c++11 -o trabalho1.exe

t25000:
	./trabalho1 25000 1
	./trabalho1 25000 2
	./trabalho1 25000 3
	./trabalho1 25000 4
	./trabalho1 25000 5
	./trabalho1 25000 6
	
