all:
	g++ mainList.cpp hash_map.cpp timer.cpp -std=c++11

list:
	g++ mainList.cpp hash_map.cpp timer.cpp -std=c++11 -o list

tree:
	g++ mainTree.cpp hash_map.cpp timer.cpp -std=c++11 -o tree

hash:
	g++ mainHash.cpp hash_map.cpp timer.cpp -std=c++11 -o hashTree
